name: Greet EveryOne

on:[push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      -name: Hello World
       uses: actions/hello-world-javascript-action@v1
       with:
         who-to-greet: 'Mona the Octocat'
       id: hello
      -name: Echo the greeting's name 
       run: echo 'the time was ${{steps.hello.outputs.time}}.'
